name: rwkv_mobile_flutter
description: 'A new Flutter package project.'
version: 0.0.1
homepage: null

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.3
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      linux:
        ffiPlugin: true

flutter_intl:
  enabled: false
