name: scripts
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  archive: ^4.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
