othello:
  app_icon: assets/icon/icon.othello.png
  bundle_id_android: com.rwkv.zone
  bundle_id_ios: com.rwkv.othello.v7.ios
  app_name: RWKV Othello

chat:
  app_icon: assets/icon/icon.chat.png
  bundle_id_android: com.rwkvzone.chat
  bundle_id_ios: com.rwkv.chat.v7.ios
  app_name: RWKV Chat

app_icon: [assets/icon/icon.othello.png, assets/icon/icon.chat.png]
bundle_id_ios: [com.rwkv.zone, com.rwkv.chat.v7.100m]
bundle_id_android: [com.rwkvzone.othello, com.rwkvzone.chat]
app_name: [RWKV Othello, RWKV Chat]
