othello:
  bundle_id_ios: com.rwkv.zone
  bundle_id_android: com.rwkv.zone
  app_icon: assets/icon/icon.othello.png
  server_address: https://othello-api.yourcompany.com
  app_name: RWKV Othello

chat:
  bundle_id_ios: com.rwkv.chat.v7.100m
  bundle_id_android: com.rwkv.zone
  app_icon: assets/icon/icon.chat.png
  server_address: https://chat-api.yourcompany.com
  app_name: RWKV Chat
