lane :all do |params|
  envString = params[:env] || "chat"
  change_analysis_options()
  dart_fix()
  change_analysis_options()
  build_number = increase_build_number()
  push_to_git_remote()
  global_replace(env: envString) # 替换环境变量
  build_assets() # 构建 assets

  # 🔥 上传到 TestFlight
  ios_upload(groups: ["External"])

  # 🔥 上传到蒲公英
  android_pgyer()

  git_reset()
  git_pull()
end

lane :dart_fix do
  sh "cd ..;dart fix --apply;cd fastlane"
end

lane :git_reset do
  sh "cd ..;git add .;git add .;git reset --hard;cd #{Dir.pwd}"
end

lane :build_assets do
  sh "cd ..;dart run flutter_native_splash:create;cd fastlane"
  sh "cd ..;dart run icons_launcher:create;cd fastlane"
end

lane :change_analysis_options do
  raw_change_analysis_options()
end

lane :increase_build_number do
  new_build_number = increase_build_version()
  git_add(path: ".")
  git_commit(
    path: ".",
    message: "_",
  )
  # 这个一定要调用吗?
  # 可能在远端触发 CI/CD 是更好的选择
  # push_to_git_remote()
end

lane :ios_upload do |params|
  run_flutter_build_ipa()
  build_app(
    project: "./ios/Runner.xcodeproj",
    skip_build_archive: true,
    archive_path: "./build/ios/archive/Runner.xcarchive",
  )
  upload_to_testflight(
    skip_submission: false,
    distribute_external: params[:groups].include?("External"),
    changelog: "Bug fixes and UI improvements",
    groups: params[:groups],
    localized_build_info: {
      "default": {
        whats_new: "Bug fixes and UI improvements",
      },
      "zh-Hans": {
        whats_new: "修复已知问题，提升用户体验",
      },
    },
  )
end

lane :android_pgyer do
  run_flutter_build_apk()
  pgyer(
    api_key: "8d0497fc24901e6b22c8f272d04791bb",
    apk: "./build/app/outputs/flutter-apk/app-release.apk",
  )
end

lane :global_replace do |params|
  global_config_replace(env: params[:env])
end

lane :switch_env do |params|
  raw_switch_android_files(env: params[:env])
  global_replace(env: params[:env])
  build_assets()
end

lane :test do |params|
  android_pgyer()
end

lane :message_to_slack do |params|
  slack(
    message: params[:message],
    slack_url: "https://hooks.slack.com/services/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",
    default_payloads: [],
  )
end
