lane :all do
  change_analysis_options()
  dart_fix()
  change_analysis_options()
  increase_build_number()
  generate_icon()
  generate_splash()
  # 🔥 iOS
  # puts "🔥🔥🔥 Start building iOS app for TestFlight External 🔥🔥🔥"
  # ios_beta_external()
  # 🔥 Android APK, pgyer
  puts "🔥🔥🔥 Start building Android APK for pgyer 🔥🔥🔥"
  android_pgyer()

  git_reset()
end

lane :dart_fix do
  sh "cd ..;dart fix --apply;cd fastlane"
end

lane :generate_icon do
  sh "cd ..;flutter pub run flutter_launcher_icons:main;cd fastlane"
end

lane :generate_splash do
  sh "cd ..;flutter pub run flutter_native_splash:create;cd fastlane"
end

lane :git_reset do
  sh "git add .;git reset --hard;git clean -fd"
end

lane :change_app_name do
  # TODO: @halo
end

lane :change_app_icon do
  # TODO: @halo
end

lane :change_app_id do
  # TODO: @halo
end

lane :change_analysis_options do
  raw_change_analysis_options()
end

lane :increase_build_number do
  new_build_number = increase_build_version()
  git_add(path: ".")
  git_commit(
    path: ".",
    message: "_",
  )
  # 这个一定要调用吗?
  # 可能在远端触发 CI/CD 是更好的选择
  # push_to_git_remote()
end

lane :ios_beta_external do
  run_flutter_build_ipa()
  build_app(
    project: "./ios/Runner.xcodeproj",
    skip_build_archive: true,
    archive_path: "./build/ios/archive/Runner.xcarchive",
  )
  upload_to_testflight(
    skip_submission: true,
    distribute_external: true,
    changelog: "Bug fixes and UI improvements",
    groups: "External",
    localized_build_info: {
      "default": {
        whats_new: "Bug fixes and UI improvements",
      },
      "zh-Hans": {
        whats_new: "修复已知问题，提升用户体验",
      },
    },
  )
end

lane :android_pgyer do
  run_flutter_build_apk()
  pgyer(
    api_key: "8d0497fc24901e6b22c8f272d04791bb",
    apk: "./build/app/outputs/flutter-apk/app-release.apk",
  )
end
